server:
  port: 8080
  servlet:
    session.timeout: 60000
    #contextpath: /ibike
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
    accesslog:
      dir: ../log
      enabled: true
      pattern: "%h %l %u %t %s %b %D \"%r\" \"%{i,Referer}\" \"%{i,User-Agent}\""
      prefix: ibike_access
      suffix: .log
      rotate: true


logging:
  level:
    root: info
    org.springframework: info
    com.yc: info
  file:
    path: ../log/yc74ibike.log



swagger:
  enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ibike?serverTimezone=UTC
    username: root
    password: a
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  data:
    mongodb:
      #host: 192.168.36.200
      #port: 27017
      uri: mongodb://192.168.36.200:23000,192.168.36.201:23000,192.168.36.202:23000/yc74ibike?readPreference=secondaryPreferred
      database: yc74ibike
  redis:
    cluster:
      nodes: 192.168.36.200:6379,192.168.36.201:6379,192.168.36.202:6379,192.168.36.203:6379,192.168.36.200:6380,192.168.36.201:6380,
      max-redirects: 3
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

mybatis-plus:
  type-aliases-package: com.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl